version: '3'
services: 
  mongo:
    image: mongo
    restart: always
  server:
    build: 
      context: .
      dockerfile: server.Dockerfile
    restart: always
    volumes: 
      - .:/app
      - /app/node_modules
    ports: 
      - "5000:5000"
    environment: 
      PORT: 5000
      MONGODB_SERVICE: mongo